export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS'
export const FETCH_CAMPAIGNS_SUCCESS = 'FETCH_CAMPAIGNS_SUCCESS'
export const FETCH_CAMPAIGNS_ERROR = 'FETCH_CAMPAIGNS_ERROR'

export const ADD_CAMPAIGNS = 'ADD_CAMPAIGNS'
export const ADD_CAMPAIGNS_SUCCESS = 'ADD_CAMPAIGNS_SUCCESS'
export const ADD_CAMPAIGNS_ERROR = 'ADD_CAMPAIGNS_ERROR'

export const SEARCH_BY_NAME = 'SEARCH_BY_NAME'
export const SEARCH_BY_NAME_SUCCESS = 'SEARCH_BY_NAME_SUCCESS'
export const SEARCH_BY_NAME_ERROR = 'SEARCH_BY_NAME_ERROR'

export const SEARCH_BY_DATE = 'SEARCH_BY_DATE'
export const SEARCH_BY_DATE_SUCCESS = 'SEARCH_BY_DATE_SUCCESS'
export const SEARCH_BY_DATE_ERROR = 'SEARCH_BY_DATE_ERROR'