export const FETCH_RESULTS = 'FETCH_RESULTS'
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS'
export const FETCH_RESULTS_ERROR = 'FETCH_RESULTS_ERROR'

export const FETCH_PLACE = 'FETCH_LOCATION'
export const FETCH_PLACE_SUCCESS = 'FETCH_LOCATION_SUCCESS'
export const FETCH_PLACE_ERROR = 'FETCH_LOCATION_ERROR'
