export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS'
export const FETCH_CAMPAIGNS_SUCCESS = 'FETCH_CAMPAIGNS_SUCCESS'
export const FETCH_CAMPAIGNS_ERROR = 'FETCH_CAMPAIGNS_ERROR'

export const ADD_CAMPAIGNS = 'ADD_CAMPAIGNS'
export const ADD_CAMPAIGNS_SUCCESS = 'ADD_CAMPAIGNS_SUCCESS'
export const ADD_CAMPAIGNS_ERROR = 'ADD_CAMPAIGNS_ERROR'

export const FILTER_CAMPAIGNS = 'FILTER_CAMPAIGNS'
export const FILTER_CAMPAIGNS_SUCCESS = 'FILTER_CAMPAIGNS_SUCCESS'
export const FILTER_CAMPAIGNS_ERROR = 'FILTER_CAMPAIGNS_ERROR'